### ISSUE TITLE
Git submodule update

### ISSUE THREAD

**Issue by szaghi** [giacombum/WenOOF#6]
You are not using the latest _master_ release of WenOOF git submodule, please update to the master branches.

To be sure you'll always point to the _master_ releases, modify your `.gitmodules` configuration as following:

``` ini
[submodule "external/pyplot-fortran"]
  path = src/third_party/pyplot-fortran
  url = https://github.com/jacobwilliams/pyplot-fortran
  branch = master
[submodule "src/third_party/PENF"]
  path = src/third_party/PENF
  url = https://github.com/szaghi/PENF
  branch = master
```

Note the additions of `branch = master` option.

**Comment by giacrossi** [comment]
Done in commit dd12540b40e68be4eb13aa757f87e6b5558cb75f
