### ISSUE TITLE
src/lib/type_weno_interpolator_js.f90(205): error #6547 

### ISSUE THREAD

**Issue by szaghi** [giacombum/WenOOF#7]
in https://github.com/giacombum/WenOOF/blob/master/src/lib/type_weno_interpolator_js.f90#L205 you are trying to do `allocated` on a pointer... you **must** use **associated** instead of `allocated`. As a matter of fact the member `JS` is a pointer, see https://github.com/giacombum/WenOOF/blob/master/src/lib/type_weno_interpolator.f90#L33

**Comment by giacrossi** [comment]
Corrected in d09e2ea87ef560544bbe9502e563adddedb6ffcf and 146e49b53b7bea81b8bae838b94f3ae7fb48ffa5
