### ISSUE TITLE
src/lib/type_weno_interpolator_js.f90(206): error #6784

### ISSUE THREAD

**Issue by szaghi** [giacombum/WenOOF#8]
when you invoke a _method_, namely a TBP, you are implicitly passing an argument (if nopass is explicitely used), thus here https://github.com/giacombum/WenOOF/blob/master/src/lib/type_weno_interpolator_js.f90#L206 you are doing a simple error...

``` fortran
    call self%IS%destroy(self%IS) ! wrong
    call self%IS%destroy ! right : self%IS is passed!
```

**Comment by giacrossi** [comment]
Corrected in d09e2ea87ef560544bbe9502e563adddedb6ffcf
